In [2]:
import pandas as pd
import numpy as np

In [3]:
df= pd.read_csv(r'C:\Users\IT BD\Downloads\listings.csv', encoding = 'unicode_escape')

In [4]:
df.head()

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,27934,Nice room with superb city view,120437.0,1462510092038582770,Nuttee,NaN,Ratchathewi,13.75983,100.54134,Entire home/apt,1573.0,30.0,65,2024-09-17,0.38,1.0,362.0,0.0,NaN
1,47516,Beautiful waterfront house,214456.0,1462512829250853525,Anuradha,NaN,Don Mueang,13.92726,100.58529,Entire home/apt,NaN,3.0,0,NaN,NaN,1.0,365.0,0.0,NaN
2,48736,Condo with Chaopraya River View,222005.0,1462513037327478070,Athitaya,NaN,Rat Burana,13.68556,100.49535,Private room,1949.0,7.0,1,2014-02-03,0.01,1.0,365.0,0.0,NaN
3,55681,Sathorn Terrace Apartment(61),263049.0,1462514155486597322,Tor,NaN,Bang Rak,13.71934,100.5176,Private room,2368.0,2.0,44,2026-04-15,0.24,4.0,337.0,6.0,NaN
4,105042,Central Bangkok 3 Bedroom Apartment,545890.0,1462521309775343192,Henry,NaN,Khlong Toei,13.73378,100.56303,Entire home/apt,4326.0,28.0,147,2020-01-07,0.82,1.0,332.0,0.0,NaN

In [5]:
df.tail()

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
31065,1715691621079565343,"No. 203(down) , a shared bunk bed (2 story)",1.690379e+18,1712277199670411448,W-Star Bangkok,NaN,Din Daeng,13.756830,100.55924,Shared room,399.0,1.0,0,NaN,NaN,7.0,365.0,0.0,NaN
31066,1715719658426126228,"No. 301, a private room with a detached W/C",1.690379e+18,1712277199670411448,W-Star Bangkok,NaN,Din Daeng,13.756827,100.5527091,Private room,1197.0,1.0,0,NaN,NaN,7.0,364.0,0.0,NaN
31067,1715734890724194650,"New Open Deal! 5ppl 2BR 2Bath Gym, Pool #BTS/MRT",6.947492e+08,1470731048185416370,Aittinan,NaN,Vadhana,13.738969,100.5664384,Entire home/apt,3378.0,1.0,0,NaN,NaN,3.0,355.0,0.0,NaN
31068,1715744450519990118,"No. 302, a private room with a detached W/C",1.690379e+18,1712277199670411448,W-Star Bangkok,NaN,Din Daeng,13.756827,100.5592382,Private room,1200.0,1.0,0,NaN,NaN,7.0,365.0,0.0,NaN
31069,1715744641593981774,Proud Room/cave luminous Near KMUTT,1.715744e+18,1715744499686398172,Proudrampa,NaN,Thung khru,13.651416,100.486531,Private room,913.0,1.0,0,NaN,NaN,1.0,365.0,0.0,NaN

In [6]:
df['neighbourhood_group'].value_counts()

neighbourhood_group
Huai Khwang    1
Name: count, dtype: int64

In [7]:
df['license'].value_counts().sum()

np.int64(0)

In [8]:
df.columns

Index(['id', 'name', 'host_id', 'host_profile_id', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'latitude', 'longitude',
       'room_type', 'price', 'minimum_nights', 'number_of_reviews',
       'last_review', 'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='str')

In [9]:
df=df[['id', 'name', 'host_id', 'host_profile_id', 'host_name',
       'neighbourhood', 'latitude', 'longitude',
       'room_type', 'price', 'minimum_nights', 'number_of_reviews',
       'last_review', 'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm']]

In [10]:
df.head()

,id,name,host_id,host_profile_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm
0,27934,Nice room with superb city view,120437.0,1462510092038582770,Nuttee,Ratchathewi,13.75983,100.54134,Entire home/apt,1573.0,30.0,65,2024-09-17,0.38,1.0,362.0,0.0
1,47516,Beautiful waterfront house,214456.0,1462512829250853525,Anuradha,Don Mueang,13.92726,100.58529,Entire home/apt,NaN,3.0,0,NaN,NaN,1.0,365.0,0.0
2,48736,Condo with Chaopraya River View,222005.0,1462513037327478070,Athitaya,Rat Burana,13.68556,100.49535,Private room,1949.0,7.0,1,2014-02-03,0.01,1.0,365.0,0.0
3,55681,Sathorn Terrace Apartment(61),263049.0,1462514155486597322,Tor,Bang Rak,13.71934,100.5176,Private room,2368.0,2.0,44,2026-04-15,0.24,4.0,337.0,6.0
4,105042,Central Bangkok 3 Bedroom Apartment,545890.0,1462521309775343192,Henry,Khlong Toei,13.73378,100.56303,Entire home/apt,4326.0,28.0,147,2020-01-07,0.82,1.0,332.0,0.0

In [11]:
nan_fill = ['price','minimum_nights','number_of_reviews','last_review', 'reviews_per_month',	
            'calculated_host_listings_count','availability_365','number_of_reviews_ltm'] 
df[nan_fill] = df[nan_fill].fillna(0)

In [12]:
df.head()

,id,name,host_id,host_profile_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm
0,27934,Nice room with superb city view,120437.0,1462510092038582770,Nuttee,Ratchathewi,13.75983,100.54134,Entire home/apt,1573.0,30.0,65,2024-09-17,0.38,1.0,362.0,0.0
1,47516,Beautiful waterfront house,214456.0,1462512829250853525,Anuradha,Don Mueang,13.92726,100.58529,Entire home/apt,0.0,3.0,0,0,0.00,1.0,365.0,0.0
2,48736,Condo with Chaopraya River View,222005.0,1462513037327478070,Athitaya,Rat Burana,13.68556,100.49535,Private room,1949.0,7.0,1,2014-02-03,0.01,1.0,365.0,0.0
3,55681,Sathorn Terrace Apartment(61),263049.0,1462514155486597322,Tor,Bang Rak,13.71934,100.5176,Private room,2368.0,2.0,44,2026-04-15,0.24,4.0,337.0,6.0
4,105042,Central Bangkok 3 Bedroom Apartment,545890.0,1462521309775343192,Henry,Khlong Toei,13.73378,100.56303,Entire home/apt,4326.0,28.0,147,2020-01-07,0.82,1.0,332.0,0.0

In [13]:
df.describe()

,host_id,latitude,price,minimum_nights,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm
count,3.106900e+04,31069.000000,3.107000e+04,31070.000000,31070.000000,31070.000000,31070.000000,31070.000000
mean,1.903928e+16,13.747115,2.757782e+03,12.781236,0.675061,32.450402,276.870035,5.878725
std,1.781249e+17,0.494275,1.841973e+04,34.339105,1.740454,49.413549,108.812330,17.839317
min,1.498300e+04,13.600390,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.934601e+07,13.720248,9.260000e+02,1.000000,0.000000,3.000000,217.000000,0.000000
50%,2.648650e+08,13.739801,1.491000e+03,2.000000,0.200000,10.000000,333.000000,1.000000
75%,5.486454e+08,13.757830,2.400000e+03,20.000000,0.810000,41.000000,364.000000,5.000000
max,1.718980e+18,100.581450,1.320255e+06,1115.000000,150.180000,247.000000,365.000000,1189.000000

In [14]:
df.dtypes

id                                    str
name                                  str
host_id                           float64
host_profile_id                       str
host_name                             str
neighbourhood                         str
latitude                          float64
longitude                             str
room_type                             str
price                             float64
minimum_nights                    float64
number_of_reviews                  object
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count    float64
availability_365                  float64
number_of_reviews_ltm             float64
dtype: object

In [20]:
# Fix data types

df['minimum_nights'] = df['minimum_nights'].astype('Int64')

df['number_of_reviews'] = pd.to_numeric(df['number_of_reviews'], errors='coerce')

df['number_of_reviews'] = df['number_of_reviews'].astype('Int64')

df['last_review'] = pd.to_datetime(df['last_review'],format='%Y-%m-%d',errors='coerce')

df['number_of_reviews_ltm'] = df['number_of_reviews_ltm'].astype('Int64')

In [21]:
df.dtypes

id                                           str
name                                         str
host_id                                  float64
host_profile_id                              str
host_name                                    str
neighbourhood                                str
latitude                                 float64
longitude                                    str
room_type                                    str
price                                    float64
minimum_nights                             Int64
number_of_reviews                          Int64
last_review                       datetime64[us]
reviews_per_month                        float64
calculated_host_listings_count           float64
availability_365                         float64
number_of_reviews_ltm                      Int64
dtype: object

In [22]:
df.head()

,id,name,host_id,host_profile_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm
0,27934,Nice room with superb city view,120437.0,1462510092038582770,Nuttee,Ratchathewi,13.75983,100.54134,Entire home/apt,1573.0,30,65,2024-09-17,0.38,1.0,362.0,0
1,47516,Beautiful waterfront house,214456.0,1462512829250853525,Anuradha,Don Mueang,13.92726,100.58529,Entire home/apt,0.0,3,0,NaT,0.00,1.0,365.0,0
2,48736,Condo with Chaopraya River View,222005.0,1462513037327478070,Athitaya,Rat Burana,13.68556,100.49535,Private room,1949.0,7,1,2014-02-03,0.01,1.0,365.0,0
3,55681,Sathorn Terrace Apartment(61),263049.0,1462514155486597322,Tor,Bang Rak,13.71934,100.5176,Private room,2368.0,2,44,2026-04-15,0.24,4.0,337.0,6
4,105042,Central Bangkok 3 Bedroom Apartment,545890.0,1462521309775343192,Henry,Khlong Toei,13.73378,100.56303,Entire home/apt,4326.0,28,147,2020-01-07,0.82,1.0,332.0,0

In [23]:

# Remove duplicates

n_before = len(df)
df = df.drop_duplicates(subset=['id'], keep='first')
print(f"Duplicates removed: {n_before - len(df)}")

Duplicates removed: 0

In [24]:
#  Standardise data

df['host_name']    = df['host_name'].str.strip().str.title()
df['neighbourhood'] = df['neighbourhood'].str.strip()

In [25]:
#  Fix invalid values

df['price'] = df['price'].abs()

In [26]:
#  Handle missing values

df['price'] = df['price'].replace(0,df['price'].mean())

df = df.dropna(subset=['host_id'])

In [34]:
df.to_csv('airbnb_listing_cleaned.csv', index=False)